---
title: "Stat 3303 Homework 6"
author: "Patrick McHugh"
date: "February 28, 2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
salaries <- read.table("C:/Users/pmchu/Documents/Stat_3303/salaries.txt",header=T)
sal <- salaries$Salary
sals <- vector("list")
numSals <- length(sal)
depts <- as.factor(salaries$Dept)
deptNums <- as.numeric(depts)
numDepts <- length(unique(deptNums))
numInDepts <- as.vector(table(deptNums))

salMatrix <- matrix(c(NA), ncol=numDepts,nrow=max(numInDepts))
for (i in 1:numDepts){
  temp <- sal[which(deptNums == i)]
  col <- c(temp, rep(NA, nrow(salMatrix)-length(temp)))
  salMatrix[,i] <- col
}

# hyperparameters
mu <- 110
tau2 <- 625
alpha <- 3
beta <- 10

dataList <- list("salMatrix" = salMatrix, "deptNums"=deptNums, "numDepts"=numDepts, "numInDepts"=numInDepts)
# list of parameters to be monitored  
parameters <- c("theta", "mu", "sigma2", "tau2")

# set initial values
initsValues <- list("theta" = rep(0,numDepts), "mu"=110, "sigma2" = 100, "tau2"=100)

# number of iteration for "tuning" 
adaptSteps <- 5000 

# number of iterations for "burn-in" 
burnInSteps <- 5000   

# number of chains to run
nChains <- 2          

# total number of iterations to save
numSavedSteps <- 5000           

# "thinning" (1 = keep every interation)
thinSteps <- 1                  

# iterations per chain
ITER <- ceiling((numSavedSteps * thinSteps )/ nChains) 

# -------------
# Run JAGS
# -------------

# create, initialize, and adapt the model
jagsModel <- jags.model("C:/Users/pmchu/Documents/Stat_3303/salaries_model.txt", data = dataList, inits = initsValues, n.chains = nChains, n.adapt = adaptSteps)

# burn-in the algorithm
update(jagsModel, n.iter = burnInSteps)

# run algorithm to get interations for inference
codaSamples <- coda.samples(jagsModel, variable.names = parameters, n.iter = ITER, thin = thinSteps)

# -------------
# Look at posterior samples
# -------------

# make a dataframe with the posterior samples
mcmcChainDF <- data.frame(as.matrix(codaSamples, iters = T, chains = T))

# create a vector with the variable names
varNames <- names(mcmcChainDF)[3:(dim(mcmcChainDF)[2])]

# number of variables
nVars <- length(varNames)

mcmcChainDF$CHAIN <- as.factor(mcmcChainDF$CHAIN)

# construct trace plots
par(ask = T)
  for( i in 1:nVars ){
    print(ggplot(mcmcChainDF, aes( x = ITER, y = mcmcChainDF[ ,varNames[i]])) +
            geom_line(aes(color = CHAIN)) + 
            labs(y = varNames[i]))
    flush.console()
  }

#get posterior samples of sigma2 = 1/prec
mcmcChainDF$sigma2 <- 1/mcmcChainDF$prec

# plot the posterior density of theta and sigma2

p_theta <- ggplot(mcmcChainDF, aes(x = theta)) +
              geom_density( color = "red") +
              geom_histogram( aes(y = ..density.. ),alpha = .3) +
              labs( main = "theta" )
           
p_sigma2 <- ggplot(mcmcChainDF, aes(x = sigma2)) +
            geom_density( color = "red") +
            geom_histogram( aes(y = ..density.. ),alpha = .3) +
            labs( main = "sigma2" )

par( ask = F )
grid.arrange(p_theta, p_sigma2, ncol = 1)

```