---
title: "Homework 7"
author: "Tyler Poelking"
date: "3/25/2018"
output:
  word_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

QUESTION 2
```{r model}
set.seed(23422432)

library(rjags)
library(boot)
library(ggplot2)
library(grid)
library(gridExtra)
library(reshape2)

# read in the data and calculate some
# summaries
friendsData <- read.table( "~/Desktop/All Stuff/School Stuff/STATS/3303/homework7/friends.txt", header=T )
y <- friendsData$y
school <- friendsData$school
x <- friendsData$x

nS <- length(unique(school))
nTotal <- length(y)

# create objects for JAGS
dataList <- list( "y" = y,
                  "x" = x,
                  "school" = school,
                  "nS" = nS,
                  "nTotal" = nTotal)

# list of parameters to be monitored  
parameters <- c( "alpha", 
                 "beta",
                 "mu_alpha",
                 "mu_beta",
                 "sigma2_alpha",
                 "sigma2_beta")

# set initial values
initsValues <- list( "alpha" = rep(0, nS), 
                     "beta" = rep(0, nS),
                     "mu_alpha" = 0,
                     "mu_beta" = 0,
                     "sigma2_alpha" = 1,
                     "sigma2_beta" = 1)

# number of iteration for "tuning" 
adaptSteps <- 5000 

# number of iterations for "burn-in" 
burnInSteps <- 5000   

# number of chains to run
nChains <- 2          

# total number of iterations to save
numSavedSteps <- 5000           

# "thinning" (1 = keep every interation)
thinSteps <- 1                  

# iterations per chain
ITER <- ceiling( (numSavedSteps * thinSteps) / nChains ) 

# -------------
# Run JAGS
# -------------

# create, initialize, and adapt the model
jagsModel <- jags.model( "~/Desktop/All Stuff/School Stuff/STATS/3303/homework7/model.txt", 
                         data = dataList, 
                         inits = initsValues, 
                         n.chains = nChains, 
                         n.adapt = adaptSteps )
```


```{r model2 }
# burn-in the algorithm
update( jagsModel, 
        n.iter = burnInSteps )

# run algorithm to get interations for inference
codaSamples <- coda.samples( jagsModel, 
                             variable.names = parameters, 
                             n.iter = ITER, 
                             thin = thinSteps )

# -------------
# Look at posterior samples
# -------------

# make a dataframe with the posterior samples
mcmcChainDF <- data.frame( as.matrix( codaSamples, 
                                      iters = T, 
                                      chains = T ) )

# create a vector with the variable names
varNames <- names( mcmcChainDF )[3:( dim( mcmcChainDF )[2] )]

# number of variables
nVars <- length( varNames )

mcmcChainDF$CHAIN <- as.factor(mcmcChainDF$CHAIN)

# construct trace plots
p <- list()
for( k in 1:nVars )
{
  plot_frame <- mcmcChainDF
  plot_frame$dep_var <- mcmcChainDF[ , varNames[k]]
  p[[k]] <- ggplot( plot_frame, 
                    aes( x = ITER, 
                         y = dep_var))  +
    geom_line( aes( color = CHAIN ) ) + 
    labs( y = varNames[k] )
}
```



```{r model2 }

mcmcChainDF$alphaPred <- rnorm( numSavedSteps, 
                                mcmcChainDF$mu_alpha,
                                sqrt(mcmcChainDF$sigma2_alpha))
mcmcChainDF$betaPred <- rnorm( numSavedSteps, 
                               mcmcChainDF$mu_beta,
                               sqrt(mcmcChainDF$sigma2_beta))

mcmcChainDF$predSame <- exp(mcmcChainDF$alphaPred) / 
                          (1+exp(mcmcChainDF$alphaPred))
mean(mcmcChainDF$predSame)

```